# Generated by Django 5.1.6 on 2025-02-27 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_app', '0002_request_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='fecha_ocurrencia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
